: ${BURN_BACKGROUND_COLOR_HOSTNAME:="white"}
: ${BURN_BACKGROUND_COLOR_DIR:="red"}
: ${BURN_FOREGROUND_COLOR_HOSTNAME:="red"}
: ${BURN_FOREGROUND_COLOR_DIR:="white"}

PS1='%{%K{${BURN_BACKGROUND_COLOR_HOSTNAME}}%F{${BURN_FOREGROUND_COLOR_HOSTNAME}}%} %n@%m %{%K{${BURN_BACKGROUND_COLOR_DIR}}%F{${BURN_FOREGROUND_COLOR_DIR}}%}'$'\ue0b0'' %~ %{%K{default}%F{${BURN_BACKGROUND_COLOR_DIR}}%}'$'\ue0c0''  %{%F{default}%}'
